"""Banco de dados

Revision ID: 26a2036d321c
Revises: 
Create Date: 2025-05-29 16:55:16.894205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a2036d321c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('data_cadastro', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_item', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('marmores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes__estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.Enum('Entrada', 'Saída'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_movimentacao', sa.TIMESTAMP(), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['estoque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_marmore', sa.String(length=100), nullable=False),
    sa.Column('metragem', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pedido', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('Pendente', 'Aprovado', 'Rejeitado', 'Concluído'), server_default='Pendente', nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('endereco_entrega', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('Pendente', 'Em Rota', 'Entregue', 'Atrasado'), server_default='Pendente', nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.TIMESTAMP(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('entregas')
    op.drop_table('pedidos')
    op.drop_table('movimentacoes__estoque')
    op.drop_table('marmores')
    op.drop_table('funcionarios')
    op.drop_table('estoque')
    op.drop_table('clientes')
    # ### end Alembic commands ###
